if (typeof exports === 'undefined')
    var exports = this
exports.pictures = [
    {title: {en: 'Saint Praxedis', ja: '聖プラクセディス'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Vermeer_saint_praxedis.jpg/196px-Vermeer_saint_praxedis.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/0/06/Vermeer_saint_praxedis.jpg',
    large: null,
    focus: [0.21, 0.65],
    comment: {ja: '聖プラクセディスが殉教者の遺体を清めた海綿から血を絞っている。<br>フィケレッリの作品に酷似しており、フェルメールの作品かどうかは議論がある。'},
    artist: 'Johannes Vermeer?'},
    {title: {en: 'Christ in the House of Martha and Mary', ja: 'マリアとマルタの家のキリスト'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Jan_Vermeer_van_Delft_004.jpg/213px-Jan_Vermeer_van_Delft_004.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/c/c9/Jan_Vermeer_van_Delft_004.jpg',
    large: null,
    focus: [87 / 213, 134 / 240],
    comment: {ja: '一行が歩いて行くうち、イエスはある村にお入りになった。すると、マルタという女が、イエスを家に迎え入れた。<br>彼女にはマリアという姉妹がいた。マリアは主の足もとに座って、その話に聞き入っていた。<br>マルタは、いろいろのもてなしのためせわしく立ち働いていたが、そばに近寄って言った。「主よ、わたしの姉妹はわたしだけにもてなしをさせていますが、何ともお思いになりませんか。手伝ってくれるようにおっしゃってください。」<br>主はお答えになった。「マルタ、マルタ、あなたは多くのことに思い悩み、心を乱している。<br>しかし、必要なことはただ一つだけである。マリアは良い方を選んだ。それを取り上げてはならない。」'},    
    artist: 'Johannes Vermeer'},
    {title: {en: 'Diana and her Companions', ja: 'ディアナとニンフたち'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Vermeer_-_Diana_en_haar_nimfen.jpg/261px-Vermeer_-_Diana_en_haar_nimfen.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/a/af/Vermeer_-_Diana_en_haar_nimfen.jpg',
    large: null,
    focus: [169 / 261, 208 / 240],
    comment: {ja: 'ディアナはローマ神話の狩りの女神。作品が醸し出す侵しがたい厳粛な雰囲気は、伝統的なギリシア・ローマ神話ではなく、キリスト教を連想させる'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Procuress', ja: '取り持ち女'}, 
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Jan_Vermeer_van_Delft_002.jpg/215px-Jan_Vermeer_van_Delft_002.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Jan_Vermeer_van_Delft_002.jpg/919px-Jan_Vermeer_van_Delft_002.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/8/84/Jan_Vermeer_van_Delft_002.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'A maid asleep', ja: '眠る女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Vermeer_young_women_sleeping.jpg/202px-Vermeer_young_women_sleeping.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Vermeer_young_women_sleeping.jpg/861px-Vermeer_young_women_sleeping.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/2/2f/Vermeer_young_women_sleeping.jpg',
    focus: [32 / 202, 167 / 233],
    comment: {ja: '空になったボトル、乱れたテーブル、立ち去った痕跡を残す椅子、酔って眠る女。<br>制作途中で扉の外に男と犬が描かれていたことが知られている。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'Girl reading a Letter at an Open Window', ja: '窓辺で手紙を読む女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Jan_Vermeer_van_Delft_003.jpg/183px-Jan_Vermeer_van_Delft_003.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Jan_Vermeer_van_Delft_003.jpg/783px-Jan_Vermeer_van_Delft_003.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Jan_Vermeer_van_Delft_003.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/e/ea/Jan_Vermeer_van_Delft_003.jpg',
    focus: [80 / 183, 203 / 239],
    comment: {ja: '鉢からこぼれた果実。背後を隠すカーテン。明るい窓外。不倫を暗示させる。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'View of houses in Delf', ja: '小路'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Jan_Vermeer_van_Delft_025.jpg/193px-Jan_Vermeer_van_Delft_025.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Jan_Vermeer_van_Delft_025.jpg/826px-Jan_Vermeer_van_Delft_025.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/f/f9/Jan_Vermeer_van_Delft_025.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Officer and a Laughing Girl', ja: '士官と笑う娘'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Jan_Vermeer_van_Delft_023.jpg/217px-Jan_Vermeer_van_Delft_023.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Jan_Vermeer_van_Delft_023.jpg/925px-Jan_Vermeer_van_Delft_023.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/0/03/Jan_Vermeer_van_Delft_023.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/0/03/Jan_Vermeer_van_Delft_023.jpg',
    comment: {ja: '「窓辺で手紙を読む女」と同じ服装の女性が描かれている。'},    
    artist: 'Johannes Vermeer'},
    {title: {en: 'The milkmaid', ja: '牛乳を注ぐ女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Vermeer_-_The_Milkmaid.jpg/215px-Vermeer_-_The_Milkmaid.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/a/a8/Vermeer_-_The_Milkmaid.jpg',
    large: null,
    focus: [70 / 215, 144 / 240],
    comment: {ja: '質感描写が高く評価されている有名な作品。'},    
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Wine Glass', ja: '紳士とワインを飲む女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Jan_Vermeer_van_Delft_018.jpg/280px-Jan_Vermeer_van_Delft_018.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Jan_Vermeer_van_Delft_018.jpg/1194px-Jan_Vermeer_van_Delft_018.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/1/19/Jan_Vermeer_van_Delft_018.jpg',
    focus: [24 / 280, 56 / 240],
    comment: {ja: 'ワインを飲み干す女、さらに注ぎ足そうとする男と宗教的ステンドグラスが対称的。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'The girl with a wineglass', ja: 'ワイングラスを持つ娘'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jan_Vermeer_van_Delft_006.jpg/211px-Jan_Vermeer_van_Delft_006.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/1/1f/Jan_Vermeer_van_Delft_006.jpg',
    large: null,
    focus: [135 / 211, 83 / 240],
    comment: {ja: '「紳士とワインを飲む女」と同じ部屋の出来事。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'Girl interrupted at her music', ja: '中断された音楽の稽古'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Vermeer_Girl_Interrupted_at_Her_Music.jpg/271px-Vermeer_Girl_Interrupted_at_Her_Music.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Vermeer_Girl_Interrupted_at_Her_Music.jpg/1155px-Vermeer_Girl_Interrupted_at_Her_Music.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Vermeer_Girl_Interrupted_at_Her_Music.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/1/14/Vermeer_Girl_Interrupted_at_Her_Music.jpg',
    focus: [108 / 271, 152 / 240],
    comment: {ja: '背景の画中画には片手にカードを持つキューピッドの像が描かれている。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'View on Delft', ja: 'デルフトの眺望'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vermeer-view-of-delft.jpg/288px-Vermeer-view-of-delft.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vermeer-view-of-delft.jpg/1228px-Vermeer-view-of-delft.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/a/a2/Vermeer-view-of-delft.jpg',
    comment: {ja: 'プルーストの「失われた時を求めて」の中で作家ベルゴットが「この小さな黄色い壁のように絵具をいくつも積み上げて、文章そのものを価値あるものにしなければいけなかったんだ」とつぶやき死んでいく。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'The music lesson', ja: '音楽の稽古'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Jan_Vermeer_van_Delft_014.jpg/209px-Jan_Vermeer_van_Delft_014.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Jan_Vermeer_van_Delft_014.jpg/891px-Jan_Vermeer_van_Delft_014.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/4/49/Jan_Vermeer_van_Delft_014.jpg',
    focus: [134 / 209, 69 / 240],
    comment: {ja: '鏡の中の女性の顔の向きが実際と異なる。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'Woman reading a letter', ja: '青衣の女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Vermeer%2C_Johannes_-_Woman_reading_a_letter_-_ca._1662-1663.jpg/200px-Vermeer%2C_Johannes_-_Woman_reading_a_letter_-_ca._1662-1663.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Vermeer%2C_Johannes_-_Woman_reading_a_letter_-_ca._1662-1663.jpg/854px-Vermeer%2C_Johannes_-_Woman_reading_a_letter_-_ca._1662-1663.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/d/db/Vermeer%2C_Johannes_-_Woman_reading_a_letter_-_ca._1662-1663.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Woman Holding a Balance', ja: '天秤を持つ女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Woman-with-a-balance-by-Vermeer.jpg/212px-Woman-with-a-balance-by-Vermeer.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/7/72/Woman-with-a-balance-by-Vermeer.jpg',
    large: null,
    focus: [131 / 212, 79 / 240],
    comment: {ja: '背景の画中画には「最後の審判」。人が天秤にかけられている。'},    
    artist: 'Johannes Vermeer'},
    {title: {en: 'Young Woman with a Water Pitcher', ja: '水差しを持つ女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Jan_Vermeer_van_Delft_019.jpg/213px-Jan_Vermeer_van_Delft_019.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/5/55/Jan_Vermeer_van_Delft_019.jpg',
    large: null,
    artist: 'Johannes Vermeer'},
    {title: {en: 'Woman with a lute', ja: 'リュートを調弦する女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Vermeer_-_Woman_with_a_Lute_near_a_window.jpg/209px-Vermeer_-_Woman_with_a_Lute_near_a_window.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Vermeer_-_Woman_with_a_Lute_near_a_window.jpg/893px-Vermeer_-_Woman_with_a_Lute_near_a_window.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/f/fe/Vermeer_-_Woman_with_a_Lute_near_a_window.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Woman with a pearl necklace', ja: '真珠の首飾りの女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Jan_Vermeer_van_Delft_008.jpg/210px-Jan_Vermeer_van_Delft_008.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Jan_Vermeer_van_Delft_008.jpg/895px-Jan_Vermeer_van_Delft_008.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/0/09/Jan_Vermeer_van_Delft_008.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'A lady writing', ja: '手紙を書く女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Vermeer_A_Lady_Writing.jpg/215px-Vermeer_A_Lady_Writing.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/4/43/Vermeer_A_Lady_Writing.jpg',
    large: null,
    artist: 'Johannes Vermeer'},
    {title: {en: 'Girl with the red hat', ja: '赤い帽子の女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Vermeer_-_Girl_with_a_Red_Hat.JPG/180px-Vermeer_-_Girl_with_a_Red_Hat.JPG',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Vermeer_-_Girl_with_a_Red_Hat.JPG/770px-Vermeer_-_Girl_with_a_Red_Hat.JPG',
    large: 'http://upload.wikimedia.org/wikipedia/commons/a/a3/Vermeer_-_Girl_with_a_Red_Hat.JPG',
    artist: 'Johannes Vermeer?'},
    {title: {en: 'The Girl With The Pearl Earring', ja: '真珠の耳飾の少女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg/168px-Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg/715px-Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/6/66/Johannes_Vermeer_%281632-1675%29_-_The_Girl_With_The_Pearl_Earring_%281665%29.jpg',
    focus: [106 / 168, 131 / 240],
    comment: {ja: '代表作の１つ。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Concert', ja: '合奏'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Vermeer_The_concert.JPG/209px-Vermeer_The_concert.JPG',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/c/c8/Vermeer_The_concert.JPG',
    large: null,
    comment: {ja: '盗難に遭っており、現在まで未発見。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'Girl with a Flute', ja: 'フルートを持つ女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Jan_Vermeer_van_Delft_020.jpg/212px-Jan_Vermeer_van_Delft_020.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/4/47/Jan_Vermeer_van_Delft_020.jpg',
    large: null,
    comment: {ja: 'フェルメールの真作とは見なさない研究者が多く、所蔵先でも伝フェルメールとされている。'},
    artist: 'Johannes Vermeer?'},
    {title: {en: 'The Allegory of Painting', ja: '絵画芸術'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Jan_Vermeer_van_Delft_011.jpg/201px-Jan_Vermeer_van_Delft_011.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Jan_Vermeer_van_Delft_011.jpg/859px-Jan_Vermeer_van_Delft_011.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Jan_Vermeer_van_Delft_011.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/2/2d/Jan_Vermeer_van_Delft_011.jpg',
    comment: {ja: 'フェルメールの作品中、最大かつもっとも複雑な作品。'},
    artist: 'Johannes Vermeer'},
    {title: {en: 'Study of a young woman', ja: '少女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Vermeer-Portrait_of_a_Young_Woman_.jpg/215px-Vermeer-Portrait_of_a_Young_Woman_.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Vermeer-Portrait_of_a_Young_Woman_.jpg/917px-Vermeer-Portrait_of_a_Young_Woman_.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Vermeer-Portrait_of_a_Young_Woman_.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/d/d8/Vermeer-Portrait_of_a_Young_Woman_.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Mistress and Maid', ja: '婦人と召使'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Vermeer_Lady_Maidservant_Holding_Letter.jpg/210px-Vermeer_Lady_Maidservant_Holding_Letter.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Vermeer_Lady_Maidservant_Holding_Letter.jpg/896px-Vermeer_Lady_Maidservant_Holding_Letter.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Vermeer_Lady_Maidservant_Holding_Letter.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/6/61/Vermeer_Lady_Maidservant_Holding_Letter.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Astronomer', ja: '天文学者'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Jan_Vermeer_-_The_Astronomer.JPG/213px-Jan_Vermeer_-_The_Astronomer.JPG',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/4/4b/Jan_Vermeer_-_The_Astronomer.JPG',
    large: null,
    focus: [74 / 213, 113 / 240],
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Geographer', ja: '地理学者'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Jan_Vermeer_van_Delft_009.jpg/210px-Jan_Vermeer_van_Delft_009.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Jan_Vermeer_van_Delft_009.jpg/895px-Jan_Vermeer_van_Delft_009.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/b/bd/Jan_Vermeer_van_Delft_009.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'The lacemaker', ja: 'レースを編む女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Johannes_Vermeer_-_The_lacemaker_%28c.1669-1671%29.jpg/204px-Johannes_Vermeer_-_The_lacemaker_%28c.1669-1671%29.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Johannes_Vermeer_-_The_lacemaker_%28c.1669-1671%29.jpg/653px-Johannes_Vermeer_-_The_lacemaker_%28c.1669-1671%29.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/0/03/Johannes_Vermeer_-_The_lacemaker_%28c.1669-1671%29.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Loveletter', ja: '恋文'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Vermeer%2C_Johannes_-_The_Loveletter.jpg/207px-Vermeer%2C_Johannes_-_The_Loveletter.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Vermeer%2C_Johannes_-_The_Loveletter.jpg/882px-Vermeer%2C_Johannes_-_The_Loveletter.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/4/4b/Vermeer%2C_Johannes_-_The_Loveletter.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Youg woman playing a guitar', ja: 'ギターを弾く女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Jan_Vermeer_van_Delft_013.jpg/210px-Jan_Vermeer_van_Delft_013.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Jan_Vermeer_van_Delft_013.jpg/896px-Jan_Vermeer_van_Delft_013.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/7/70/Jan_Vermeer_van_Delft_013.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'Lady writing a letter with her maid', ja: '手紙を書く婦人と召使'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/DublinVermeer.jpg/200px-DublinVermeer.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/2/2b/DublinVermeer.jpg',
    large: null,
    artist: 'Johannes Vermeer'},
    {title: {en: 'The Allegory of the Faith', ja: '信仰の寓意'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Vermeer_The_Allegory_of_the_Faith.jpg/185px-Vermeer_The_Allegory_of_the_Faith.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Vermeer_The_Allegory_of_the_Faith.jpg/791px-Vermeer_The_Allegory_of_the_Faith.jpg',
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Vermeer_The_Allegory_of_the_Faith.jpg',
    huge: 'http://upload.wikimedia.org/wikipedia/commons/5/5c/Vermeer_The_Allegory_of_the_Faith.jpg',
    focus: [146 / 185, 66 / 239],
    artist: 'Johannes Vermeer'},
    {title: {en: 'Young woman standing at a virginal', ja: 'ヴァージナルの前に立つ女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Jan_Vermeer_van_Delft_024.jpg/211px-Jan_Vermeer_van_Delft_024.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Jan_Vermeer_van_Delft_024.jpg/900px-Jan_Vermeer_van_Delft_024.jpg',
    /* large: 'http://upload.wikimedia.org/wikipedia/commons/8/8f/Jan_Vermeer_van_Delft_024.jpg', can not load on iPad. */
    large: 'http://dl.dropbox.com/u/8719413/masterpieces/images/Jan_Vermeer_van_Delft_024.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'A Lady Seated at a Virginal', ja: 'ヴァージナルの前に座る女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Jan_Vermeer_van_Delft_005.jpg/204px-Jan_Vermeer_van_Delft_005.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Jan_Vermeer_van_Delft_005.jpg/870px-Jan_Vermeer_van_Delft_005.jpg',
    large: 'http://upload.wikimedia.org/wikipedia/commons/1/17/Jan_Vermeer_van_Delft_005.jpg',
    artist: 'Johannes Vermeer'},
    {title: {en: 'A young Woman seated at the Virginals', ja: 'ヴァージナルの前に座る若い女'},
    small: 'http://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Vermeer_virginal.jpg/190px-Vermeer_virginal.jpg',
    normal: 'http://upload.wikimedia.org/wikipedia/commons/b/b8/Vermeer_virginal.jpg',
    large: null,
    artist: 'Johannes Vermeer'}
];
